= Autumn

映射 Asciidoc/Markdown 文件目录为网站，有简单的访问控制，有好用的搜索功能。

搜索功能支持单词完全匹配、句子完全匹配、通配符、排除指定词、分类、标签，还支持多条件之间与和或的逻辑。

详见 link:src/main/resources/static/help.adoc#_search[]

== 环境需求

* Java 8+
* Maven 3.5
* （可选）Redis 4

== 快速开始

[source,bash]
----
git clone git@github.com:wei345/autumn.git
cd autumn
bin/start.sh

# 停止
# bin/autumn.sh stop
----

用浏览器访问 http://localhost:8601

用户名：user，密码: 123456

== 配置

所有配置项和默认值见 src/main/resources/application.properties。

新建文件 src/main/resources/application-local.properties。

最重要的几项配置是：`autumn.data.dir`，`autumn.users` 和 `autumn.remember-me.aes-key`。

=== autumn.data.dir

一个包含 .adoc 或 .md 文件的目录路径。

.adoc 或 .md 文件会被映射为网页。例如 `${autumn.data.dir}/a/b/c.adoc` 会被映射为网页 `+http://localhost:8601/a/b/c+`。

其他文件会被视为静态文件。例如 `${autumn.data.dir}/a/b/c.png` 会被映射为 `+http://localhost:8601/a/b/c.png+`。

.adoc 文件格式示例：
[source,asciidoc]
----
= Title
:created: 2018-02-20 12:59:50 +0800
:modified: 2018-12-03 20:18:42 +0800
:category: at_most_one_category
:tags: tag1, tag2, tag3
:published: false

正文内容
----

.md 文件格式示例：
[source,markdown]
----
---
created: 2018-02-20 12:59:50
modified: 2018-12-03 20:18:42
category: at_most_one_category
tags: tag1, tag2, tag3
published: false
---

# Title

正文内容
----

published 用于访问控制，已登录用户可以看到全部页面，未登录只能看到 published 设为 true 的页面。

如果不符合以上格式，系统会自动设置默认值。`created` 和 `modified` 默认值是文件修改时间，`published` 默认值是 `false`。

=== autumn.users

生成密码:

[source,bash]
----
mvn -q -DskipTests=false -Dtest=io.liuwei.autumn.service.UserServiceTest#generateUser test
----

输出示例：

[source,text]
----
1 Username 1B62BCEB123EB08F73BE3970394C23973FADF75CDCEE153A27FD2EC808805ED29BCC77CDCB966E4C775347D55E82753510D9E8154387BB7286D8CBAF9E68324A 75F0FF8B5CF34B050491DBB9F0BBF85F;
----

`Username` 可随意修改。

=== autumn.remember-me.aes-key

生成 AES key:

[source,bash]
----
mvn -q -DskipTests=false -Dtest=io.liuwei.autumn.AesTest#generateKey test
----

输出示例：

[source,text]
----
2FDFCEF1DAA8E567549C52C10422BE09A81CC80B0A05BFE8CF75F223BD87DEB6
----

== 生产环境部署

创建配置文件 src/main/resources/application-prod.properties（也可以将其他文件 link 到这个位置），该文件应该包含以下配置：

[source,properties]
----
# /path/to/data
autumn.data.dir=<your data directory>
autumn.data.reload-interval-seconds=0
autumn.resource.reload-interval-seconds=0
# id username password salt; id ...
autumn.users=<your users>
autumn.remember-me.aes-key=<your aes key>
# 若要启用 Redis
spring.autoconfigure.exclude=
----

其中，autumn.data.reload-interval-seconds=0 禁用周期性扫描数据目录，autumn.resource.reload-interval-seconds=0 禁用周期性扫描 resources 目录。

数据目录更新时，通过 HTTP 接口触发 reload，例如：

[source,bash]
----
curl --silent -X POST http://localhost:8601/manage/data
----

== ...

=== 有那么多现成的网站工具，为什么还要自己开发？

因为都不顺手。

* Jekyll 不适合我。我只想公开一部分内容，自己能够看到全部内容，还想要不依赖第三方的好用的搜索功能。
* WordPress 不适合我。我不喜欢在网页的小窗口内编辑文本，不，大窗口也不喜欢，我更喜欢用强大的文本编辑器编辑文本。
* DokuWiki 不适合我。同上。
* 其他，试过一些，也不适合我。

我曾经改造过 DokuWiki，用 git 同步数据，自动刷新索引，把文件扩展名从 .txt 改为 .md，增加 front matter 支持，Sidebar 可折叠等。DokuWiki 有很多我不需要的功能和逻辑，对于改造来说都是负担，改造成本很高，考虑到将来要支持 category、tags、blog，还有很高的改造成本。

不如自己开发，比改造一个现有的东西更可控更省时间，每一处都按照自己的喜好来做，访问速度更快，用起来更顺手。
